// <auto-generated />
namespace Typer.Database.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DbMatchPredictionFIx : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbMatchPredictionFIx));
        
        string IMigrationMetadata.Id
        {
            get { return "201711111714399_DbMatchPredictionFIx"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
