// <auto-generated />
namespace Typer.Database.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class typercontext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(typercontext));
        
        string IMigrationMetadata.Id
        {
            get { return "201711041543112_typercontext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
