// <auto-generated />
namespace Typer.Database.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_team : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_team));
        
        string IMigrationMetadata.Id
        {
            get { return "201710031855266_add_team"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
